# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=70, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=15, verbose_name='DNI/NIF')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('phone', models.CharField(max_length=40, verbose_name='Telafono')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profesion')),
                ('created', models.TimeField(auto_now=True, verbose_name='Fecha del alta')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='participant',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contestApp.Province', verbose_name='Provincia'),
        ),
    ]
