# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestApp', '0002_auto_20161026_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='Fecha creacion')),
                ('url', models.ImageField(max_length=255, upload_to=b'', verbose_name='Ruta')),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
    ]
