# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contestApp', '0003_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='Fecha voto')),
                ('email', models.EmailField(max_length=254, verbose_name='email del votante')),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contestApp.Picture', verbose_name='Foto votada')),
            ],
        ),
    ]
