# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestApp', '0009_auto_20161027_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='votes',
            field=models.IntegerField(default=0, max_length=7),
        ),
    ]
