# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestApp', '0011_remove_picture_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='votes',
            field=models.IntegerField(default=4, max_length=7),
        ),
    ]
