# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-29 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestApp', '0017_remove_picture_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Puntos'),
        ),
    ]
