# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-29 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestApp', '0018_picture_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='points',
        ),
        migrations.AddField(
            model_name='picture',
            name='points',
            field=models.ManyToManyField(to='contestApp.Vote'),
        ),
    ]
