# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-29 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestApp', '0020_auto_20161029_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='points',
            field=models.PositiveIntegerField(verbose_name='Puntos'),
        ),
    ]
