# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-29 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestApp', '0023_remove_picture_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='url',
            field=models.ImageField(max_length=255, upload_to='upload_pictures', verbose_name='Ruta'),
        ),
    ]
