# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestApp', '0025_auto_20161029_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='created',
            field=models.DateTimeField(null=True, verbose_name='Fecha voto'),
        ),
    ]
