# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 17:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestApp', '0028_auto_20161101_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 1, 17, 37, 39, 39245), verbose_name='Fecha voto'),
        ),
    ]
