# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestApp', '0029_auto_20161101_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='created',
            field=models.DateTimeField(verbose_name='Fecha creacion'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha voto'),
        ),
    ]
