# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestApp', '0030_auto_20161101_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha del alta'),
        ),
    ]
